### ISSUE TITLE
CSF story format update

### ISSUE THREAD

**Issue by joanrm20** [sw-yx/react-typescript-storybook-starter#3]
Hey @sw-yx ,

I have updated the storybook config according to the docs using main.js, preview.js, manager.js and using CSF. 

Besides I've removed the custom Button component in favor of the ones provided by storybook react demo package and some other small updates like replacing addon-jsx and addon info by addon docs.

I was wondering if those changes are interesting for you to get in the repo then I can send a PR. 

Here my fork: https://github.com/joanrm20/react-typescript-storybook-starter

Cheers,

**Comment by swyxio** [comment]
hey! yes please send in a PR! i LOVE CSF.
